export interface OrderInterface {
    batchId: string,
    orderId: string,
    reference: string,
    batchName: string,
    brandId: string,
    totalItems: number,
    salesTax: number,
    vat: number,
    totalSales: number,
    trend: boolean,
    draftFlag: boolean,
    orderedFlag: boolean,
    processedFlag: boolean,
    category: string,
    orderNote: string,
    orderedBy: string,
    orderedDate: string,
    updatedDate: string,
}