import { OrderInterface } from "../interfaces/ordersInterface";

export const getAllOrders = async (): Promise<OrderInterface[]> => {

    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([
                {
                    batchId: "HHZ4000",
                    orderId: "523523",
                    reference: "",
                    batchName: "Luxemburgs Insanity Kit",
                    brandId: "HHS3523",
                    totalItems: 30,
                    salesTax: 0.5,
                    vat: 0,
                    totalSales: 3520,
                    trend: true,
                    draftFlag: false,
                    orderedFlag: true,
                    processedFlag: true,
                    category: "Dropship",
                    orderNote: "Lorem ipsum dolor",
                    orderedBy: "C35SsdVD35wxCsDf",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ4045",
                    orderId: "5235352",
                    reference: "",
                    batchName: "Sony A7ii Camera",
                    brandId: "SNY424",
                    totalItems: 23,
                    salesTax: 0.2,
                    vat: 0,
                    totalSales: 5234,
                    trend: false,
                    draftFlag: false,
                    orderedFlag: true,
                    processedFlag: false,
                    category: "Dropship",
                    orderNote: "Sony Camera Orders",
                    orderedBy: "fasdVsxfSdgsCvs",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ4501",
                    orderId: "629412",
                    reference: "REF1201",
                    batchName: "Canon DSLR Lens Kit",
                    brandId: "CNL1200",
                    totalItems: 15,
                    salesTax: 0.3,
                    vat: 0.1,
                    totalSales: 4240,
                    trend: true,
                    draftFlag: true,
                    orderedFlag: false,
                    processedFlag: false,
                    category: "Electronics",
                    orderNote: "Special order",
                    orderedBy: "AdfrSdxg34ZwdD",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ3205",
                    orderId: "784562",
                    reference: "",
                    batchName: "Apple iPad Pro",
                    brandId: "APL564",
                    totalItems: 12,
                    salesTax: 0.5,
                    vat: 0.2,
                    totalSales: 7865,
                    trend: false,
                    draftFlag: false,
                    orderedFlag: true,
                    processedFlag: true,
                    category: "Tablets",
                    orderNote: "Bulk order for office",
                    orderedBy: "XqwfrdfscS234",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ5000",
                    orderId: "985634",
                    reference: "REF3201",
                    batchName: "Gaming Laptops",
                    brandId: "LTP3421",
                    totalItems: 8,
                    salesTax: 0.7,
                    vat: 0.15,
                    totalSales: 12340,
                    trend: true,
                    draftFlag: false,
                    orderedFlag: false,
                    processedFlag: false,
                    category: "Computers",
                    orderNote: "Urgent requirement",
                    orderedBy: "VvsdDgw34wWswf",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ1050",
                    orderId: "347820",
                    reference: "REF4523",
                    batchName: "Wireless Headphones",
                    brandId: "HDP3421",
                    totalItems: 50,
                    salesTax: 0.3,
                    vat: 0.1,
                    totalSales: 6700,
                    trend: true,
                    draftFlag: true,
                    orderedFlag: false,
                    processedFlag: true,
                    category: "Accessories",
                    orderNote: "Large quantity",
                    orderedBy: "WsdDfwg35343",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ6780",
                    orderId: "412034",
                    reference: "",
                    batchName: "Kitchen Essentials Set",
                    brandId: "KTC232",
                    totalItems: 20,
                    salesTax: 0.1,
                    vat: 0.05,
                    totalSales: 1200,
                    trend: true,
                    draftFlag: false,
                    orderedFlag: true,
                    processedFlag: false,
                    category: "Home Appliances",
                    orderNote: "Kitchen items for export",
                    orderedBy: "TsdfdfQwVffds",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ9700",
                    orderId: "901234",
                    reference: "REF7891",
                    batchName: "Outdoor Camping Kit",
                    brandId: "ODK543",
                    totalItems: 10,
                    salesTax: 0.25,
                    vat: 0,
                    totalSales: 3400,
                    trend: true,
                    draftFlag: true,
                    orderedFlag: false,
                    processedFlag: true,
                    category: "Outdoor",
                    orderNote: "Seasonal demand",
                    orderedBy: "FvdXxfDsYyZ",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ1234",
                    orderId: "658901",
                    reference: "REF1234",
                    batchName: "Luxury Bedding Set",
                    brandId: "BDS200",
                    totalItems: 5,
                    salesTax: 0.4,
                    vat: 0.2,
                    totalSales: 5200,
                    trend: true,
                    draftFlag: false,
                    orderedFlag: true,
                    processedFlag: true,
                    category: "Furniture",
                    orderNote: "Exclusive customer order",
                    orderedBy: "XsDgwf345SdDs",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
                {
                    batchId: "HHZ5401",
                    orderId: "349560",
                    reference: "REF5673",
                    batchName: "Smart Watches",
                    brandId: "SMW430",
                    totalItems: 40,
                    salesTax: 0.15,
                    vat: 0.05,
                    totalSales: 7800,
                    trend: true,
                    draftFlag: true,
                    orderedFlag: false,
                    processedFlag: true,
                    category: "Wearable Tech",
                    orderNote: "Gift items",
                    orderedBy: "QwVfgdsD123Ds",
                    orderedDate: new Date().toISOString(),
                    updatedDate: new Date().toISOString(),
                },
            ]);
        }, 2000);
    });
};
